apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
  namespace: inventory-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
        - name: item-service
          image: rashmiabhay/item-service:1.0
          ports:
            - containerPort: 8080