apiVersion: v1
kind: Service
metadata:
  name: inventory-api-gateway
  namespace: inventory-platform
spec:
  type: NodePort
  selector:
    app: inventory-api-gateway
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090