spring.mongodb.uri=mongodb+srv://rashmiabhaykrishna_db_user:141qh7wRLhEbpnsP@item.xvjeoee.mongodb.net/Task?retryWrites=true&w=majority
server.port=8080
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
  
# =========================================
# ACTUATOR
# =========================================

logging.pattern.console=%d [%X{X-Correlation-ID}] %-5level %logger - %msg%n
management.endpoints.web.exposure.include=health,info,metrics,gateway

management.endpoint.health.show-details=always