spring.application.name=inventory-bff-service
server.port=8082

services.item-service.base-url=http://item-service:8080

services.stock-service.base-url=http://stock-service:8081

#==========Elastic search============

#spring.elasticsearch.uris=http://elasticsearch:9200
#+++++++++To disable elastic search=================
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration

# =========================================
# ACTUATOR
# =========================================

logging.pattern.console=%d [%X{X-Correlation-ID}] %-5level %logger - %msg%n
management.endpoints.web.exposure.include=health,info,metrics,gateway
logging.level.root=INFO

management.endpoint.health.show-details=always

